# Generated by Django 4.2.27 on 2026-03-17 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(blank=True, null=True, unique=True)),
                ('ol_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('pages', models.IntegerField(default=0)),
                ('blurb', models.TextField(default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('currently_reading', models.ManyToManyField(related_name='currently_reading', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readquest.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readquest.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('stage_final', models.IntegerField()),
                ('stage_current', models.IntegerField()),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='readquest.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_goal', models.CharField(default=0, max_length=200)),
                ('books', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ManyToManyField(blank=True, related_name='completed_goals', to=settings.AUTH_USER_MODEL)),
                ('current_goals', models.ManyToManyField(related_name='current_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.IntegerField()),
                ('reads', models.IntegerField()),
                ('slug', models.SlugField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='readquest.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='read_by',
            field=models.ManyToManyField(related_name='read_by', through='readquest.ReadRecord', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='wishlisted_by',
            field=models.ManyToManyField(related_name='wishlisted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('icon', models.ImageField(upload_to='')),
                ('earners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
