# Generated by Django 4.2.27 on 2026-03-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='blurb',
        ),
        migrations.RemoveField(
            model_name='book',
            name='ol_key',
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='views',
        ),
    ]
