# Generated by Django 4.2.27 on 2026-03-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0002_remove_book_blurb_remove_book_ol_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
