# Generated by Django 5.2.8 on 2026-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0003_delete_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ol_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
