# Generated by Django 5.2.8 on 2026-03-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0004_book_ol_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
